/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accesso: typeof import('./src/components/Accesso.vue')['default']
    Aggiungi: typeof import('./src/components/mete__log/Aggiungi.vue')['default']
    Benvenuto: typeof import('./src/components/Benvenuto.vue')['default']
    Cerca: typeof import('./src/components/mete__log/Cerca.vue')['default']
    Esplora: typeof import('./src/components/mete__log/Esplora.vue')['default']
    Home: typeof import('./src/components/mete__log/Home.vue')['default']
    ModifyPost: typeof import('./src/components/mete__log/modifyPost.vue')['default']
    ModifyProfilo: typeof import('./src/components/mete__log/modifyProfilo.vue')['default']
    Post: typeof import('./src/components/mete__log/post.vue')['default']
    Profilo: typeof import('./src/components/mete__log/Profilo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Voli: typeof import('./src/components/mete__log/Voli.vue')['default']
  }
}
